### ISSUE TITLE
01-Outline-Feedback

### ISSUE THREAD

**Issue by nniiicc** [PugetSoundClinic-PIT/ml-for-pit#1]
https://github.com/PugetSoundClinic-PIT/ml-for-pit/blame/81a497291d3b68080905e693f6c1c4d4ba7ae375/content/01-about-this-course.md#L18 
- Provide link with a note like "If you need to brush up on Linear Algebra, we recommend Khan Academy's free course https://www.khanacademy.org/math/linear-algebra " 

For chapters / sections 

```
    About This Course & Getting Setup
    Understanding Municipal Legislative Data
    Word Counts (And What They Can Do)
    Using State-of-the-Art Semantic Embeddings
    Creating Text Classifiers
    Applying Pre-trained Models
    Combining It All To Analyze Discussion Activity
```
Consider dropping the verbs so it is more concise
- Municipal Legislative DAta
- Word Counts (And What They Can Do) 
- State-of-the-Art Semantic Embeddings
- ...

Tense: 
- Consider plural (we, our, etc) or moving to third person... both changes serves to depersonalize the instruction ... So someone borrowing the content doesn't need to revise or feel awkward about the "I" statements that are not their actual statements

**Comment by evamaxfield** [comment]
Resolved: https://github.com/PugetSoundClinic-PIT/ml-for-pit/commit/567aca6501935145447b534c4a498db6fc143114

Minor note: I went with [3Blue1Brown's video series on linear algebra](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab) over Khan Academy's.
