### ISSUE TITLE
Semantic Embeddings (4) 

### ISSUE THREAD

**Issue by nniiicc** [PugetSoundClinic-PIT/ml-for-pit#2]
Suggestions
- [x] In the introduction - name the 3-4 techniques that will be covered 
- [x] "The examples will focus on how to use these techniques to analyze text corpora - each section will introduce a technique, give an example, refine the example explanation, and then walk through an advanced example using CDP data"
- [x] State goal "The goal of this chapter is to X" and "At the end of this chapter you will Y"
- [x] State limitations "Each technique will have a brief explanation - we provide additional materials where you can learn more about the technique" 

This lays out the order of operations for each technique/ idea: 

Semantic neighborhoods
- What are they 
- What is a simple example 
- What are they more technically in the context of ML for PIT 
- Advanced example using CDP data 

Sentence transformers
- ...

**Comment by nniiicc** [comment]
Note - I am a big advocate of the technical writing style that I call -> Double I Double E
- **Idea** - simplest straightforward introduction to a concept
- **Incomplete example** - used as an anecdote to explain the concept 
- **Elaboration** of the idea and variations - Adds detail to the 'Idea' explanation, invites discussion of edge cases, introduces technical aspects of implementation / use of the idea
- **Extended example** - As close to a real-world example of the 'Idea' as possible - incorporating one or more details from the 'Elaboration' explanation. 

*borrows heavily from http://teachtogether.tech/

**Comment by evamaxfield** [comment]
Bullet point draft pushed, wrote the draft then looked at these notes and made changes in the actual notebook. Will give this another look when everything is done.
